# -*- coding: utf-8 -*-
"""duzelt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EEf3uWPUpNKGifE8pQVjSVwutuga0_Z
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, TensorDataset, Subset
import numpy as np
from scipy.signal import convolve2d
import matplotlib.pyplot as plt
import os
import sys

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

# ── Dataset Selection ─────────────────────────────────────────────
def choose_dataset():
    print("\nSelect dataset:")
    print("  [1] CIFAR-10       (32x32,  10 classes,  auto-download ~170MB)")
    print("  [2] Tiny-ImageNet  (64x64, 200 classes,  auto-download ~240MB)")
    print()
    while True:
        choice = input("Enter 1 or 2: ").strip()
        if choice in ("1", "2"):
            return "cifar10" if choice == "1" else "tiny_imagenet"
        print("  Invalid input. Please enter 1 or 2.")

DATASET = choose_dataset()
print(f"\n→ Dataset selected: {DATASET.upper()}\n")

# ── Config per dataset ────────────────────────────────────────────
if DATASET == "cifar10":
    IMG_SIZE    = 32
    NUM_CLASSES = 10
    BATCH_SIZE  = 128
    BASE_EPOCHS = 20
    DET_EPOCHS  = 10

    MEAN_T = torch.tensor([0.4914, 0.4822, 0.4465]).view(1,3,1,1).to(DEVICE)
    STD_T  = torch.tensor([0.2023, 0.1994, 0.2010]).view(1,3,1,1).to(DEVICE)

    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])
    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])

    train_set = torchvision.datasets.CIFAR10(
        root="./data", train=True, download=True, transform=transform_train)
    test_set  = torchvision.datasets.CIFAR10(
        root="./data", train=False, download=True, transform=transform_test)

else:
    IMG_SIZE    = 64
    NUM_CLASSES = 200
    BATCH_SIZE  = 64
    BASE_EPOCHS = 20
    DET_EPOCHS  = 10

    MEAN_T = torch.tensor([0.485, 0.456, 0.406]).view(1,3,1,1).to(DEVICE)
    STD_T  = torch.tensor([0.229, 0.224, 0.225]).view(1,3,1,1).to(DEVICE)

    transform_train = transforms.Compose([
        transforms.RandomCrop(64, padding=8),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    ])
    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    ])

    try:
        from datasets import load_dataset as hf_load
    except ImportError:
        print("\n[ERROR] 'datasets' package not found.")
        sys.exit(1)

    # ── Wrapper: converts HuggingFace records → (tensor, int) ────────
    class TinyImageNetDataset(torch.utils.data.Dataset):
        """
        Wraps zh-plus/tiny-imagenet HuggingFace split.
        Each record has keys: 'image' (PIL) and 'label' (int 0-199).
        """
        def __init__(self, hf_split, transform=None):
            self.data      = hf_split
            self.transform = transform

        def __len__(self):
            return len(self.data)

        def __getitem__(self, idx):
            record = self.data[idx]
            img    = record["image"].convert("RGB")   # ensure 3-channel
            label  = record["label"]
            if self.transform:
                img = self.transform(img)
            return img, label

    print("Downloading zh-plus/tiny-imagenet from HuggingFace...")
    print("(~240 MB — cached after first run)\n")

    hf_ds     = hf_load("zh-plus/tiny-imagenet")   # returns DatasetDict
    # Splits available: 'train' (100 000 images) and 'valid' (10 000 images)
    train_set = TinyImageNetDataset(hf_ds["train"], transform=transform_train)
    test_set  = TinyImageNetDataset(hf_ds["valid"], transform=transform_test)

    print(f"  Train: {len(train_set):,} images | Val: {len(test_set):,} images")

train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True,  num_workers=4, pin_memory=True)
test_loader  = DataLoader(test_set,  batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True)

print(f"Train batches: {len(train_loader)} | Test batches: {len(test_loader)}")

# ── ResNet backbone (adaptive for both resolutions) ───────────────
class BasicBlock(nn.Module):
    def __init__(self, in_ch, out_ch, stride=1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_ch, out_ch, 3, stride=stride, padding=1, bias=False)
        self.bn1   = nn.BatchNorm2d(out_ch)
        self.conv2 = nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False)
        self.bn2   = nn.BatchNorm2d(out_ch)
        self.skip  = nn.Sequential()
        if stride != 1 or in_ch != out_ch:
            self.skip = nn.Sequential(
                nn.Conv2d(in_ch, out_ch, 1, stride=stride, bias=False),
                nn.BatchNorm2d(out_ch)
            )

    def forward(self, x):
        return F.relu(self.bn2(self.conv2(F.relu(self.bn1(self.conv1(x))))) + self.skip(x))


class ResNet18(nn.Module):
    """
    For CIFAR-10 (32x32):      small stem (3x3, stride 1), no maxpool.
    For Tiny-ImageNet (64x64): medium stem (3x3, stride 2), no maxpool —
                                one stride-2 conv halves to 32x32 before the blocks.
    """
    def __init__(self, num_classes=10, large_input=False):
        super().__init__()
        if large_input:
            # 64x64 → 32x32 with a single stride-2 3x3 conv (no maxpool needed)
            self.prep = nn.Sequential(
                nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1, bias=False),
                nn.BatchNorm2d(64), nn.ReLU(),
            )
        else:
            self.prep = nn.Sequential(
                nn.Conv2d(3, 64, 3, padding=1, bias=False),
                nn.BatchNorm2d(64), nn.ReLU()
            )
        self.layer1 = nn.Sequential(BasicBlock(64, 64),    BasicBlock(64, 64))
        self.layer2 = nn.Sequential(BasicBlock(64, 128, 2), BasicBlock(128, 128))
        self.layer3 = nn.Sequential(BasicBlock(128, 256, 2), BasicBlock(256, 256))
        self.layer4 = nn.Sequential(BasicBlock(256, 512, 2), BasicBlock(512, 512))
        self.pool   = nn.AdaptiveAvgPool2d(1)
        self.fc     = nn.Linear(512, num_classes)

    def forward(self, x):
        x = self.prep(x)
        x = self.layer1(x); x = self.layer2(x)
        x = self.layer3(x); x = self.layer4(x)
        return self.fc(self.pool(x).view(x.size(0), -1))


# ── PGD Attack ───────────────────────────────────────────────────
def pgd_attack(model, images, labels, eps=8/255, alpha=2/255, steps=20):
    model.eval()
    adv = torch.clamp(images + torch.empty_like(images).uniform_(-eps, eps), 0, 1)
    for _ in range(steps):
        adv.requires_grad_(True)
        F.cross_entropy(model(adv), labels).backward()
        adv = torch.clamp(
            images + torch.clamp(adv.detach() + alpha * adv.grad.sign() - images, -eps, eps),
            0, 1
        ).detach()
    return adv


# ── Second-Round Attack (Carlini et al.) ─────────────────────────
def second_round_attack(base_model, detector, images, labels,
                        eps=8/255, alpha=2/255, steps=40):
    base_model.eval(); detector.eval()
    adv = torch.clamp(images + torch.empty_like(images).uniform_(-eps, eps), 0, 1)
    for _ in range(steps):
        adv.requires_grad_(True)
        z_base = base_model(adv)
        z_det  = detector(adv)
        adv_score  = (z_det[:, 1] - z_det[:, 0]).unsqueeze(1)
        extra_logit = (adv_score + 1) * z_base.max(dim=1, keepdim=True).values
        g = torch.cat([z_base, extra_logit], dim=1)
        loss = F.cross_entropy(g, labels)
        loss.backward()
        adv = torch.clamp(
            images + torch.clamp(adv.detach() + alpha * adv.grad.sign() - images, -eps, eps),
            0, 1
        ).detach()
    return adv


# ── SRM Features ─────────────────────────────────────────────────
KERNELS = [
    np.array([[0, 0, 0], [0, -1, 1], [0, 0, 0]], dtype=np.float32),
    np.array([[0, 0, 0], [0, -1, 0], [0, 1, 0]], dtype=np.float32),
    np.array([[0, 0, 0], [0, -1, 0], [0, 0, 1]], dtype=np.float32),
    np.array([[0, 0, 0], [1, -2, 1], [0, 0, 0]], dtype=np.float32),
    np.array([[0, 1, 0], [0, -2, 0], [0, 1, 0]], dtype=np.float32),
]

def srm_features(images_np, T=4, q=1):
    """Works on any spatial resolution: (N, C, H, W) numpy array in [0,1]."""
    feats = []
    for img in images_np:
        f = []
        for c in range(img.shape[0]):
            for k in KERNELS:
                r = np.clip(
                    np.round(convolve2d(img[c], k, mode='same', boundary='symm') / q),
                    -T, T
                ).astype(int)
                hist, _ = np.histogram(r, bins=np.arange(-T, T + 2), density=True)
                f.append(hist)
        feats.append(np.concatenate(f))
    return np.array(feats, dtype=np.float32)


def fisher_select(Fc, Fa, dim=30):
    scores = (Fc.mean(0) - Fa.mean(0))**2 / (Fc.var(0) + Fa.var(0) + 1e-8)
    return np.argsort(scores)[::-1][:dim]


# ── Wavelet Features (Haar DWT) ───────────────────────────────────
def compute_haar_features(x):
    """Spatial-resolution independent: returns (N, 3*4*2) = (N, 24) features."""
    k_ll = torch.tensor([[1., 1.], [1., 1.]]).view(1, 1, 2, 2) / 4.0
    k_lh = torch.tensor([[1., -1.], [1., -1.]]).view(1, 1, 2, 2) / 4.0
    k_hl = torch.tensor([[1., 1.], [-1., 1.]]).view(1, 1, 2, 2) / 4.0
    k_hh = torch.tensor([[1., -1.], [-1., 1.]]).view(1, 1, 2, 2) / 4.0
    filters = torch.cat([k_ll, k_lh, k_hl, k_hh], dim=0).to(x.device)

    features = []
    for c in range(x.shape[1]):
        xc = x[:, c:c+1, :, :]
        subbands = F.conv2d(xc, filters, stride=2)
        features.append(torch.mean(subbands, dim=[2, 3]))
        features.append(torch.std(subbands, dim=[2, 3]))
    return torch.cat(features, dim=1)


# ── Detectors ────────────────────────────────────────────────────
class Detector(nn.Module):
    """CNN-only detector; uses AdaptiveAvgPool so works on any resolution."""
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 64, 5, padding=2, bias=False); self.bn1 = nn.BatchNorm2d(64)
        self.conv2 = nn.Conv2d(64, 128, 3, padding=1, bias=False); self.bn2 = nn.BatchNorm2d(128)
        self.conv3 = nn.Conv2d(128, 256, 3, stride=2, padding=1, bias=False); self.bn3 = nn.BatchNorm2d(256)
        self.pool  = nn.AdaptiveAvgPool2d(1)
        self.fc    = nn.Linear(256, 2)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        return self.fc(self.pool(x).view(x.size(0), -1))


class DetectorFusion(nn.Module):
    def __init__(self, srm_dim):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 64, 5, padding=2, bias=False); self.bn1 = nn.BatchNorm2d(64)
        self.conv2 = nn.Conv2d(64, 128, 3, padding=1, bias=False); self.bn2 = nn.BatchNorm2d(128)
        self.conv3 = nn.Conv2d(128, 256, 3, stride=2, padding=1, bias=False); self.bn3 = nn.BatchNorm2d(256)
        self.pool  = nn.AdaptiveAvgPool2d(1)
        self.fc    = nn.Linear(256 + srm_dim, 2)

    def forward(self, x_img, x_srm):
        x = F.relu(self.bn1(self.conv1(x_img)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        x = self.pool(x).view(x.size(0), -1)
        return self.fc(torch.cat([x, x_srm], dim=1))


class DetectorWavelet(nn.Module):
    def __init__(self, wavelet_dim):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 64, 5, padding=2, bias=False); self.bn1 = nn.BatchNorm2d(64)
        self.conv2 = nn.Conv2d(64, 128, 3, padding=1, bias=False); self.bn2 = nn.BatchNorm2d(128)
        self.conv3 = nn.Conv2d(128, 256, 3, stride=2, padding=1, bias=False); self.bn3 = nn.BatchNorm2d(256)
        self.pool  = nn.AdaptiveAvgPool2d(1)
        self.fc    = nn.Linear(256 + wavelet_dim, 2)

    def forward(self, x_img, x_wave):
        x = F.relu(self.bn1(self.conv1(x_img)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        x = self.pool(x).view(x.size(0), -1)
        return self.fc(torch.cat([x, x_wave], dim=1))


class DetectorTripleFusion(nn.Module):
    def __init__(self, wavelet_dim, srm_dim):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 64, 5, padding=2, bias=False); self.bn1 = nn.BatchNorm2d(64)
        self.conv2 = nn.Conv2d(64, 128, 3, padding=1, bias=False); self.bn2 = nn.BatchNorm2d(128)
        self.conv3 = nn.Conv2d(128, 256, 3, stride=2, padding=1, bias=False); self.bn3 = nn.BatchNorm2d(256)
        self.pool  = nn.AdaptiveAvgPool2d(1)
        self.fc    = nn.Linear(256 + wavelet_dim + srm_dim, 2)

    def forward(self, x_img, x_wave, x_srm):
        x = F.relu(self.bn1(self.conv1(x_img)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        x_cnn = self.pool(x).view(x.size(0), -1)
        return self.fc(torch.cat([x_cnn, x_wave, x_srm], dim=1))


# ── Train Base Model ──────────────────────────────────────────────
large_input = (DATASET == "tiny_imagenet")
base_model  = ResNet18(num_classes=NUM_CLASSES, large_input=large_input).to(DEVICE)
opt         = torch.optim.Adam(base_model.parameters(), lr=1e-3)
scheduler   = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=BASE_EPOCHS)

print(f"Training Base Model ({BASE_EPOCHS} epochs)...")
for epoch in range(BASE_EPOCHS):
    base_model.train()
    running_loss = 0.0
    for imgs, lbls in train_loader:
        imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
        opt.zero_grad()
        loss = F.cross_entropy(base_model(imgs), lbls)
        loss.backward()
        opt.step()
        running_loss += loss.item()
    scheduler.step()
    if (epoch + 1) % max(1, BASE_EPOCHS // 4) == 0:
        avg_loss = running_loss / len(train_loader)
        print(f"  Epoch {epoch+1}/{BASE_EPOCHS}  loss={avg_loss:.4f}")

# ── Build Detector Dataset ────────────────────────────────────────
print("\nBuilding detector dataset (PGD attacks on test set)...")
all_imgs, all_lbls = [], []

for batch_i, (imgs, lbls) in enumerate(test_loader):
    imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
    imgs_01 = torch.clamp(imgs * STD_T + MEAN_T, 0, 1)
    adv_01  = pgd_attack(base_model, imgs_01, lbls)
    all_imgs.append(torch.cat([imgs_01, adv_01]).cpu())
    all_lbls.extend([0] * len(imgs) + [1] * len(imgs))
    if (batch_i + 1) % 20 == 0:
        print(f"  Processed {batch_i+1}/{len(test_loader)} batches...")

all_imgs = torch.cat(all_imgs)          # (2N, C, H, W)
all_lbls = torch.tensor(all_lbls)       # (2N,)
print(f"Detector dataset: {len(all_imgs)} samples ({all_imgs.shape})")

# ── SRM Features ─────────────────────────────────────────────────
print("\nComputing SRM features...")
# For ImageNet (224x224), SRM is expensive; use a fast numpy batch path
srm_all = srm_features(all_imgs.numpy())
srm_idx = fisher_select(srm_all[all_lbls == 0], srm_all[all_lbls == 1], dim=30)
srm_all = srm_all[:, srm_idx]
print(f"SRM feature dim after Fisher selection: {srm_all.shape[1]}")

# ── Wavelet Features ──────────────────────────────────────────────
print("Computing Wavelet features...")
wavelet_all = compute_haar_features(all_imgs.to(DEVICE)).cpu()
print(f"Wavelet feature dim: {wavelet_all.shape[1]}")

srm_tensor = torch.from_numpy(srm_all).float()

# ── Train All Four Detectors ──────────────────────────────────────
def train_detector(model, loader, optimizer, epochs, name):
    print(f"\nTraining {name} ({epochs} epochs)...")
    model.train()
    for epoch in range(epochs):
        for batch in loader:
            *features, lbls = [b.to(DEVICE) for b in batch]
            optimizer.zero_grad()
            out = model(*features)
            F.cross_entropy(out, lbls).backward()
            optimizer.step()
        if (epoch + 1) % max(1, epochs // 2) == 0:
            print(f"  {name} epoch {epoch+1}/{epochs}")


# Standard CNN detector
detector    = Detector().to(DEVICE)
det_opt     = torch.optim.Adam(detector.parameters(), lr=1e-3)
det_data    = DataLoader(TensorDataset(all_imgs, all_lbls), batch_size=BATCH_SIZE, shuffle=True)
train_detector(detector, det_data, det_opt, DET_EPOCHS, "Standard CNN Detector")

# SRM Fusion
detector_fusion   = DetectorFusion(srm_dim=srm_tensor.shape[1]).to(DEVICE)
det_opt_fusion    = torch.optim.Adam(detector_fusion.parameters(), lr=1e-3)
det_data_fusion   = DataLoader(TensorDataset(all_imgs, srm_tensor, all_lbls), batch_size=BATCH_SIZE, shuffle=True)
train_detector(detector_fusion, det_data_fusion, det_opt_fusion, DET_EPOCHS, "Fusion Detector (SRM)")

# Wavelet Fusion
detector_wavelet  = DetectorWavelet(wavelet_dim=wavelet_all.shape[1]).to(DEVICE)
det_opt_wavelet   = torch.optim.Adam(detector_wavelet.parameters(), lr=1e-3)
det_data_wavelet  = DataLoader(TensorDataset(all_imgs, wavelet_all, all_lbls), batch_size=BATCH_SIZE, shuffle=True)
train_detector(detector_wavelet, det_data_wavelet, det_opt_wavelet, DET_EPOCHS, "Fusion Detector (Wavelet)")

# Triple Fusion
detector_triple   = DetectorTripleFusion(wavelet_all.shape[1], srm_tensor.shape[1]).to(DEVICE)
det_opt_triple    = torch.optim.Adam(detector_triple.parameters(), lr=1e-3)
det_data_triple   = DataLoader(TensorDataset(all_imgs, wavelet_all, srm_tensor, all_lbls), batch_size=BATCH_SIZE, shuffle=True)
train_detector(detector_triple, det_data_triple, det_opt_triple, DET_EPOCHS, "Triple Fusion Detector")

# ── Evaluation helper ─────────────────────────────────────────────
base_model.eval()
detector.eval(); detector_fusion.eval()
detector_wavelet.eval(); detector_triple.eval()

def eval_all_detectors(loader):
    counts = {
        "std":    [0, 0, 0],
        "srm":    [0, 0, 0],
        "wave":   [0, 0, 0],
        "triple": [0, 0, 0],
    }
    total = 0

    for batch_i, (imgs, lbls) in enumerate(loader):
        imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
        imgs_01 = torch.clamp(imgs * STD_T + MEAN_T, 0, 1)

        adv_01  = pgd_attack(base_model, imgs_01, lbls)
        adv2_01 = second_round_attack(base_model, detector, imgs_01, lbls)
        total  += lbls.size(0)

        # SRM features
        srm_c  = torch.from_numpy(srm_features(imgs_01.cpu().numpy())[:, srm_idx]).float().to(DEVICE)
        srm_a  = torch.from_numpy(srm_features(adv_01.cpu().numpy())[:, srm_idx]).float().to(DEVICE)
        srm_a2 = torch.from_numpy(srm_features(adv2_01.cpu().numpy())[:, srm_idx]).float().to(DEVICE)

        # Wavelet features
        wv_c  = compute_haar_features(imgs_01)
        wv_a  = compute_haar_features(adv_01)
        wv_a2 = compute_haar_features(adv2_01)

        with torch.no_grad():
            # Standard
            counts["std"][0] += detector(imgs_01).argmax(1).eq(0).sum().item()
            counts["std"][1] += detector(adv_01).argmax(1).eq(1).sum().item()
            counts["std"][2] += detector(adv2_01).argmax(1).eq(1).sum().item()

            # SRM Fusion
            counts["srm"][0] += detector_fusion(imgs_01, srm_c).argmax(1).eq(0).sum().item()
            counts["srm"][1] += detector_fusion(adv_01, srm_a).argmax(1).eq(1).sum().item()
            counts["srm"][2] += detector_fusion(adv2_01, srm_a2).argmax(1).eq(1).sum().item()

            # Wavelet Fusion
            counts["wave"][0] += detector_wavelet(imgs_01, wv_c).argmax(1).eq(0).sum().item()
            counts["wave"][1] += detector_wavelet(adv_01, wv_a).argmax(1).eq(1).sum().item()
            counts["wave"][2] += detector_wavelet(adv2_01, wv_a2).argmax(1).eq(1).sum().item()

            # Triple Fusion
            counts["triple"][0] += detector_triple(imgs_01, wv_c, srm_c).argmax(1).eq(0).sum().item()
            counts["triple"][1] += detector_triple(adv_01, wv_a, srm_a).argmax(1).eq(1).sum().item()
            counts["triple"][2] += detector_triple(adv2_01, wv_a2, srm_a2).argmax(1).eq(1).sum().item()

        if (batch_i + 1) % 10 == 0:
            print(f"  Evaluated {batch_i+1}/{len(loader)} batches...")

    accs = {k: [100. * v / total for v in vals] for k, vals in counts.items()}
    return accs, total


print(f"\n{'='*60}")
print(f"Evaluating all detectors on {DATASET.upper()} test set...")
print(f"{'='*60}")
accs, total = eval_all_detectors(test_loader)

std_clean_acc,    std_pgd_acc,    std_2nd_acc    = accs["std"]
fus_clean_acc,    fus_pgd_acc,    fus_2nd_acc    = accs["srm"]
wav_clean_acc,    wav_pgd_acc,    wav_2nd_acc    = accs["wave"]
triple_clean_acc, triple_pgd_acc, triple_2nd_acc = accs["triple"]

# ── Print Results Table ───────────────────────────────────────────
print("\n" + "="*90)
ds_label = "CIFAR-10" if DATASET == "cifar10" else "Tiny-ImageNet (zh-plus, 64x64, 200-cls)"
print(f"  Results on {ds_label}  (total={total} samples)")
print("="*90)
print(f"{'Metric':<20} | {'Standard':<12} | {'SRM Fusion':<12} | {'Wave Fusion':<12} | {'Triple Fusion':<13}")
print("-"*90)
print(f"{'Clean Accuracy':<20} | {std_clean_acc:<12.2f}% | {fus_clean_acc:<12.2f}% | {wav_clean_acc:<12.2f}% | {triple_clean_acc:<12.2f}%")
print(f"{'PGD Detection':<20} | {std_pgd_acc:<12.2f}% | {fus_pgd_acc:<12.2f}% | {wav_pgd_acc:<12.2f}% | {triple_pgd_acc:<12.2f}%")
print(f"{'2nd-Round Detect':<20} | {std_2nd_acc:<12.2f}% | {fus_2nd_acc:<12.2f}% | {wav_2nd_acc:<12.2f}% | {triple_2nd_acc:<12.2f}%")
print("="*90 + "\n")

# ── Plot ──────────────────────────────────────────────────────────
labels_plot = ['Clean', 'PGD Attack', '2nd-Round Attack']
x           = np.arange(len(labels_plot))
width       = 0.20

fig, ax = plt.subplots(figsize=(14, 6))
r1 = ax.bar(x - 1.5*width, accs["std"],    width, label='Standard CNN')
r2 = ax.bar(x - 0.5*width, accs["srm"],    width, label='Fusion (SRM + CNN)')
r3 = ax.bar(x + 0.5*width, accs["wave"],   width, label='Fusion (Wavelet + CNN)')
r4 = ax.bar(x + 1.5*width, accs["triple"], width, label='Triple Fusion (All)')

ax.set_ylabel('Detection Accuracy (%)')
ax.set_title(f'Detector Performance Comparison — {ds_label}')
ax.set_xticks(x)
ax.set_xticklabels(labels_plot)
ax.legend()
ax.set_ylim([0, 110])

def autolabel(rects):
    for rect in rects:
        h = rect.get_height()
        ax.annotate(f'{h:.1f}%',
                    xy=(rect.get_x() + rect.get_width() / 2, h),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontsize=8)

for r in [r1, r2, r3, r4]:
    autolabel(r)

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig(f"detector_comparison_{DATASET}.png", dpi=150)
print(f"Plot saved → detector_comparison_{DATASET}.png")
plt.show()